### ISSUE TITLE
tws_delayMicroseconds?

### ISSUE THREAD

**Issue by mattgilbertnet** [rambo/TinyWire#8]
This is really a feature request more than an "issue".

This is surely a low priority, if it's even a concern for anyone other than me, but is there any chance of a tws_delayMicroseconds() being implemented?

**Comment by jockm** [comment]
This is just a nit, but wouldn't the naive loop be better written precalculating the end time?:
```
tws_delayMicroseconds_inaccurate(uint16_t usec)
{
    uint16_t stopMicros = (uint16_t)micros() + usec;
    while (((uint16_t)micros()) < stopMicros)
    {
        TinyWireS_stop_check();
    }
}
```

**Comment by carycode** [comment]
@jockm: Please don't use "`(((uint16_t)micros()) < stopMicros)`", because that leads to *occasional* difficult-to-debug glitches when TinyWireS_stop_check() takes more than 1 microsecond. For example, if we try to delay usec = 9 microseconds, and the first micros() call gives us 0xFFF6, this code sets "stopMicros" to 0xFFFF, and TinyWireS_stop_check() plus the loop overhead takes 2 microseconds, then this precalculating approach ends up stuck in the loop for over 65,000 microseconds (possibly forever), which is not what we wanted. The "`((uint16_t)((uint16_t)micros() - start) < usec)`" properly handles rollover even with TinyWireS_stop_check(); taking anywhere from practically 0 to nearly 16,000 microseconds. See https://arduino.stackexchange.com/questions/12587/how-can-i-handle-the-millis-rollover and https://stackoverflow.com/questions/61443/rollover-safe-timer-tick-comparisons and https://www.baldengineer.com/arduino-how-do-you-reset-millis.html for more details.

**Comment by jockm** [comment]
@carycode Fair point, but you should note that I was just copying rambo's style from above.  This comment is better addressed there
